# Generated by Django 2.0.7 on 2018-08-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH_OPTION'), ('CARD', 'ATM_CARD_OPTION'), ('WALLET', 'DIGITAL_PAYMENT')], default='CASH', max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('amount', models.IntegerField()),
                ('expense_time', models.DateTimeField(blank=True)),
                ('category', models.CharField(choices=[('FOOD', 'FOOD & DRINK'), ('FUEL', 'PETROL OR DIESEL'), ('ENTERTAINMENT', 'ENTERTAINMENT')], default='FOOD', max_length=50)),
            ],
        ),
    ]
